management:
  endpoint:
  endpoints:
    web:
      base-path: /application

---
spring:
  config:
    activate:
      on-profile: real1
  profiles:
    active: local
    include:
      - secret
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: real2
  profiles:
    active: local
    include:
      - secret
server:
  port: 8082